version: '3'
services:
  geojsonconverter:
    build: .
    image: jpo_geojsonconverter:latest
    # ports:
    #   - "9090:9090"
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
    logging:
      options:
        max-size: "10m"
        max-file: "5"
