version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic.ProcessedSpat:1:1,topic.ProcessedMap:1:1,topic.ProcessedMapWKT:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  geojsonconverter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN_NAME: ${GITHUB_TOKEN_NAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_ORG: ${GITHUB_ORG}
    image: jpo_geojsonconverter:latest
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      geometry.output.mode: ${GEOMETRY_OUTPUT_MODE}
      spring.kafka.bootstrap-servers: ${DOCKER_HOST_IP}:9092
    logging: 
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - kafka
