version: '3'
services:
  geojsonconverter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_ORG: ${GITHUB_ORG}
    restart: always
    image: jpo_geojsonconverter:latest
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      geometry.output.mode: ${GEOMETRY_OUTPUT_MODE}
      spring.kafka.bootstrap-servers: ${DOCKER_HOST_IP}:9092
    logging: 
      options:
        max-size: "10m"
        max-file: "5"
