version: '3'
services:
  geojsonconverter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_ORG: ${GITHUB_ORG}
    image: jpo_geojsonconverter:latest
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      KAFKA_TYPE: ${KAFKA_TYPE}
      CONFLUENT_KEY: ${CONFLUENT_KEY}
      CONFLUENT_SECRET: ${CONFLUENT_SECRET}
      geometry.output.mode: ${GEOMETRY_OUTPUT_MODE}
    logging: 
      options:
        max-size: "10m"
        max-file: "5"
