name: Docker build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  jpo-geojsonconverter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            GITHUB_TOKEN_NAME=${{ secrets.MAVEN_GITHUB_TOKEN }}
            GITHUB_TOKEN=${{ vars.MAVEN_GITHUB_TOKEN_NAME }}
            GITHUB_ORG=${{ github.repository_owner }}
          secrets: |
            MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}